### ISSUE TITLE
Incorrect info for mbpfan package

### ISSUE THREAD

**Issue by jlbuckner** [rpmsphere/x86_64#1]
The package summary for `mbpfan` is incorrect. It shows "Free Sony PlayStation emulator". 

It should read something like what is listed in the Arch AUR: "Automatically adjust the fan on a MacBook Pro".

Specific file at issue: `mbpfan-1.5.0-4.1.x86_64.rpm`

**Comment by bluebat** [comment]
fix and update:
https://github.com/rpmsphere/x86_64/raw/master/m/mbpfan-2.1.1-1.x86_64.rpm
