### ISSUE TITLE
Link to download and enable repository is broken.

### ISSUE THREAD

**Issue by telometto** [rpmsphere/x86_64#3]
As the title states: the [link](https://github.com/rpmsphere/noarch/raw/master/r/rpmsphere-release-34-1.noarch.rpm) is broken and the project's page doesn't explain where to grab the file itself. I can edit the `/etc/yum.repos.d/rpmsphere.repo` file but I can't recall which of the options I should enable for the default settings... is it `[rpmsphere]` and `[rpmsphere-noarch]`?

**Comment by bluebat** [comment]
filename should be https://github.com/rpmsphere/noarch/raw/master/r/rpmsphere-release-34-2.noarch.rpm
fixed.
