### ISSUE TITLE
imagescan won't install on F35 - outdated boost dependencies

### ISSUE THREAD

**Issue by gloomytrousers** [rpmsphere/x86_64#4]
`dnf install imagescan` fails on F35:
```
Error: 
 Problem: conflicting requests
  - nothing provides libboost_filesystem.so.1.75.0()(64bit) needed by imagescan-3.38.0-1.x86_64
  - nothing provides libboost_program_options.so.1.75.0()(64bit) needed by imagescan-3.38.0-1.x86_64
  - nothing provides libboost_system.so.1.75.0()(64bit) needed by imagescan-3.38.0-1.x86_64
```

F35 has boost-filesystem-1.76.0-4.fc35.x86_64, boost-program-options-1.76.0-4.fc35.x86_64 and boost-system-1.76.0-4.fc35.x86_64 which provides those libraries, but a later version.

Additionally this version of imagescan is severely outdated (from 2018!); Epson has version 3.65 available ([SRPMs](http://support.epson.net/linux/src/scanner/imagescanv3/fedora/) up to F32, [source](http://support.epson.net/linux/src/scanner/imagescanv3/common/)). The [Utushi repo on GitHub](https://github.com/utsushi/imagescan) (referenced in the RPM) has stopped tracking releases - it's readonly and points to [GitLab](https://gitlab.com/utsushi/imagescan/) which *has* been updated to 3.65.

**Comment by bluebat** [comment]
updated to 3.65.0
