### ISSUE TITLE
error installing libcob-3.0rc1-16.1.x86_64.rpm

### ISSUE THREAD

**Issue by victorsosa** [rpmsphere/x86_64#6]
Hi,
Having this issue installing this package

Downloading Packages:
[MIRROR] libcob-3.0rc1-16.1.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 173185 but expected size is: 174332                               
[MIRROR] libcob-3.0rc1-16.1.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 173185 but expected size is: 174332                               
[MIRROR] libcob-3.0rc1-16.1.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 173185 but expected size is: 174332                               
[MIRROR] libcob-3.0rc1-16.1.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 173185 but expected size is: 174332                               
[FAILED] libcob-3.0rc1-16.1.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success                                                          

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download l/libcob-3.0rc1-16.1.x86_64.rpm: All mirrors were tried

same issue trying to install the libcob-devel-3.0rc1-16.1.x86_64.rpm too

**Comment by bluebat** [comment]
Packages: gnucobol, libcob, libcob-devel
installed OK on Fedora 32
