### ISSUE TITLE
Package not working

### ISSUE THREAD

**Issue by linux4678** [rpmsphere/x86_64#7]
hello the xtrlock package doesn't work on f37 and didn't work on f36 either. When I type in xtrlock in the terminal I get
bash: xtrlock: command not found
Install package 'xtrlock' to provide command 'xtrlock'? [N/y]
When I attempt to reinstall I can't because I'm not root and when I do it from root I get the response that it's already installed. Last complaint for a while promise!
thank you
linux4678

**Comment by bluebat** [comment]
Thanks for reporting.
Fixed and updated:
https://github.com/rpmsphere/x86_64/raw/master/x/xtrlock-2.15-1.x86_64.rpm
