### ISSUE TITLE
gitea rpm's gitea binary doesn't have all style sheets.

### ISSUE THREAD

**Issue by finjulhich** [rpmsphere/x86_64#8]
The binary downloaded from gitea's own download site is bigger and more complete.

Can you please fix?

**Comment by bluebat** [comment]
I use this spec file for building the package.
https://github.com/rpmsphere/spec/blob/master/g/gitea.spec
Could you give me any suggestion?

**Comment by finjulhich** [comment]
Hello, I'm not sure. There were many assets missing from the rpm's bin. Its size is smaller than the one I downloaded directly from gitea.
```
ll /usr/bin/gitea*
-rwxr-xr-x. 1 root root 131344136 Aug 31 11:24 /usr/bin/gitea
-rwxr-xr-x. 1 root root  93697928 Jul 23 01:00 /usr/bin/gitea.rpmsave
```

rpm's binary close to 90MB while from gitea binary is 130MB.

**Comment by bluebat** [comment]
which asset missing?
binary from Gitea after strip is only 100MB
updated to 1.20.4
