### ISSUE TITLE
'stressapptest' complains of "reduced coverage" and thus needs to be run with "-A" arg

### ISSUE THREAD

**Issue by FlippityFlipFlopFly** [rpmsphere/x86_64#9]
Hi. Would you please consider recompiling 'stressapptest' with -DNDEBUG ?

Currently, with `stressapptest-1.0.9-2.1.x86_64.rpm` on Fedora 32 live cd, I get the message that `-A` argument is required to run it, here's the code:
https://github.com/stressapptest/stressapptest/blob/c8ce5af2c2ac12377d1c229f8be73410acdd00ff/src/sat.cc#L108-L123

damn, github is broken for me: "Nothing to preview"
hope this works...

**Comment by bluebat** [comment]
updated.
